// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Raphael
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "raphael_bindings";



        [DllImport(__DllName, EntryPoint = "solve", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void solve(SolveArgs* args);


    }

    [StructLayout(LayoutKind.Sequential)]
    public unsafe partial struct SolveArgs
    {
        public delegate* unmanaged[Cdecl]<bool*, void> on_start;
        public delegate* unmanaged[Cdecl]<Action*, nuint, void> on_finish;
        public delegate* unmanaged[Cdecl]<Action*, nuint, void> on_suggest_solution;
        public delegate* unmanaged[Cdecl]<nuint, void> on_progress;
        public delegate* unmanaged[Cdecl]<byte*, nuint, void> on_log;
        public LevelFilter log_level;
        public ushort thread_count;
        public ulong action_mask;
        public ushort progress;
        public ushort quality;
        public ushort base_progress;
        public ushort base_quality;
        public ushort cp;
        public ushort durability;
        public byte job_level;
        [MarshalAs(UnmanagedType.U1)] public bool adversarial;
        [MarshalAs(UnmanagedType.U1)] public bool backload_progress;
    }


    public enum Action : byte
    {
        BasicSynthesis,
        BasicTouch,
        MasterMend,
        Observe,
        TricksOfTheTrade,
        WasteNot,
        Veneration,
        StandardTouch,
        GreatStrides,
        Innovation,
        WasteNot2,
        ByregotsBlessing,
        PreciseTouch,
        MuscleMemory,
        CarefulSynthesis,
        Manipulation,
        PrudentTouch,
        AdvancedTouch,
        Reflect,
        PreparatoryTouch,
        Groundwork,
        DelicateSynthesis,
        IntensiveSynthesis,
        TrainedEye,
        HeartAndSoul,
        PrudentSynthesis,
        TrainedFinesse,
        RefinedTouch,
        QuickInnovation,
        ImmaculateMend,
        TrainedPerfection,
    }

    public enum LevelFilter : byte
    {
        Off,
        Error,
        Warn,
        Info,
        Debug,
        Trace,
    }


}
